language: node_js
node_js: 5.5.0
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
install: npm install
before_script: grunt build
after_script: cat ./build/coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false